
FROM python


WORKDIR /app

# COPY requirements.txt /app/
COPY ./Backend /app
RUN pip install --no-cache-dir -r requirements.txt

# COPY . /app/

EXPOSE 8000

CMD ["uvicorn", "main:main", "--host", "0.0.0.0", "--port", "8000"]